learning_log/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('learning_logs.urls')),
    path('users/', include('users.urls'))
    
]

learning_logs/urls.py
"""defines url patterns for learning_logs"""

from django.urls import path#this func help us when mapping urls to views
from . import views

app_name = 'learning_logs'#helps Django distinguish this urls.py file from files of the same name in other apps within the project

urlpatterns = [
    #home page
    path('', views.index , name='index' ),#se the book for the explanation of the args
    #topic page
    path('topics/', views.topics, name='topics'),
    #individual topic page
    path('topics/<int:topic_id>/', views.topic, name='topic'),#the url will use the topic id attribute to show which topic was requested
                                                            #to do this we use <int:topic_id> as topic_id s are int
    #new topic url (when users wanna create a new topic)
    path('new_topic/', views.new_topic, name='new_topic'),
    #new entry url. we use the int topic_id because we can add multiple entries
    path('new_entry/<int:topic_id>', views.new_entry, name='new_entry'),
    path('edit_entry/<int:entry_id>', views.edit_entry, name='edit_entry' )
]#this variable urlspatterns is a list of individual page that can be requested to learning_logs app
 

users/urls.py
from django.urls import path, include
from . import views
app_name = 'users'

urlpatterns = [
    #include the default auth urls(as we want to use django 's default login view )
    path('', include('django.contrib.auth.urls')),
    #registration page url
    path('register/', views.register, name='register')
]

learning_logs/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
#a models tell django how to works with the data that will be stored in the currents app.
#see the book for more explanation.
class Topic(models.Model):
    """a topic the user is learning about """
    text = models.CharField(max_length=200)#this create a string field for small to large sized of string(such as name, city...) and its arg tell django how much space it should reserve in the database
    date_added = models.DateTimeField(auto_now_add=True)#this record the date and time the arg tell django to automativally set this attr to the current date and time 
    owner = models.ForeignKey(User, on_delete=models.CASCADE)#a foreign key relation btw user and topic
    def __str__(self):
        """returning a string representation of the model """
        return self.text

class Entry(models.Model):
    """something specific leaned about the topic"""
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)#This is the code that connects each entry to a specific topic
    text = models.TextField()#this reserve a large text field in the db
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'entries'
    
    def __str__(self):
        return self.text[:50] + '...'

users/models.py
from django.db import models

# Create your models here.

learning_logs/forms.py
from django import forms
from .models import Topic, Entry#importig the models that we wanna work with

class TopicForm(forms.ModelForm):#defining a class that inherits from forms.ModelForm
                                #The simplest version of a ModelForm consists of a nested Meta class telling Django which model to base the form on and which fields to include in the form
    class Meta:
        model = Topic#we build a form from the Topic mode
        fields = ['text']#we include only the text fields in the forms
        labels = {'text': ''}#we tell to djnago to not generate a label for the text field

class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        label = {'text' : 'Entry : '}#we want the form to add a label 'entry'
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}#we use the forms.Textarea of the widget and add cols attrs of 80  to give users much space

learning_logs/views.py
from django.shortcuts import render, redirect
#We import the function redirect, which we’ll use to redirect the user back to the topics 
#page after they submit their topic. The redirect() function takes in the name of a view and redirects the user to that view
from .models import Topic#We first import the model associated with the data we need
from .models import Entry
from .forms import TopicForm, EntryForm#We also import the form we just wrote, TopicForm.
from django.contrib.auth.decorators import login_required
from django.http import Http404
# Create your views here.

def index(request):
    """the home page fpr learning log"""
    return render(request, 'learning_logs/index.html')

@login_required
def topics(request):
    """show all the topics"""
    topics = Topic.objects.filter(owner=request.user).order_by('date_added')#we query the database by asking for the Topic objects sorted by the date_added attribute
    context = {'topics' : topics }#context is a dict that key is the name we ll use in the template to access data and value is a data that we need to send in the template. here is the topics.
    return render(request, 'learning_logs/topics.html', context)
@login_required
def topic(request, topic_id):#we pass also topic_id in arg because the func accept the value captured by <int:topic_id> and store it in topic_id
    """show the indivuadual topic and its entry"""
    topic = Topic.objects.get(id=topic_id)#we are retrieving the topic by id 
    if topic.owner != request.user:
        raise Http404

    entries =  topic.entry_set.order_by('-date_added')#we get entries associated with this topic
                                            #the minus in front of date_added sort the result in reverse order which display by most recent
    context = {'topic': topic, 'entries': entries}#storing topic and entries in context
    return render(request, 'learning_logs/entries.html', context )#sending context to template
@login_required
def new_topic(request):
    """add a new topic"""
    if request.method != 'POST':#we check if the request method is Get or post(see book for explanation of these keyword).
                                #if request isnt Post , then its probably Get so we return a blank form even if its not post, its safe to reurn a blank
        form = TopicForm()##no data submitted , create a blank form
    else:
        #post data submitted ; process data
        form = TopicForm(data=request.POST)
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save()
            return redirect('learning_logs:topics')
    #display a blank or invalid form
    context = {'form': form}
    return render(request, 'learning_logs/new_topic.html', context)

@login_required
def new_entry(request, topic_id):

    topic = Topic.objects.get(id=topic_id)
    if topic.owner != request.user:
        raise Http404
    if request.method != 'POST':
        form = EntryForm()
    else:
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return redirect('learning_logs:topic', topic_id=topic_id)
    context = {'form': form, 'topic': topic}
    return render(request, 'learning_logs/new_entry.html', context)

@login_required
def edit_entry(request, entry_id):
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic

    if topic.owner != request.user:
        raise Http404
    #initial requests; pre-fill form with current entry
    if request.method != 'POST':
        form = EntryForm(instance=entry)
    else:
        form = EntryForm(instance=entry , data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('learning_logs:topic', topic_id=topic.id)
    context = {'form': form, 'entry':entry, 'topic': topic}
    return render(request, 'learning_logs/edit_entry.html', context)

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import  login
from django.contrib.auth.forms import UserCreationForm
# Create your views here.
def register(request):
    if request.method != 'POST':
        form = UserCreationForm()
    else:
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            new_user = form.save()
            #login the new users
            login(request, new_user)
            #redirect to home page logged in
            return redirect('learning_logs:index')

    context = {'form': form}
    return render(request,'registration/register.html', context)

learning_logs/templates/learning_logs/base.html
{% load bootstrap4 %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1,
      shrink-to-fit=no">
    <title>Learning Log</title>
    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}
</head>
<body>
  <nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">
    <a class="navbar-brand"  href="{% url 'learning_logs:index' %}"> Learning Log</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse"
      data-target="#navbarCollapse" aria-controls="navbarCollapse"
      aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'learning_logs:topics'%}">Topics</a>
        </li>
      </ul>
      <ul class="navbar-nav ml-auto">
        {% if user.is_authenticated %}
          <li class="nav-item">
            <span class="navbar-text">Hello, {{ user.username }}.</span>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'users:logout' %}">Log out</a>
          </li>
        {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'users:register' %}">Register</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'users:login' %}">Log in</a>
          </li>
         {% endif %}
      </ul>
    </div>

  </nav>
  <main role="main" class="container">
    <div class="pb-2 mb-2 border-bottom">
     {% block page_header %}{% endblock page_header %}
    </div>
    <div>
     {% block content %}{% endblock content %}
    </div>
  </main>
</body>
</html>

learning_logs/templates/learning_logs/edit_entry.html
{% extends "learning_logs/base.html" %}
{% load bootstrap4 %}

{% block page_header %}
 <h2>Log in to your account.</h2>
{% endblock page_header %}
{% block content %}
  <h3><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></h3>

  <h4>Edit entry:</h4>

  <form method='post' action="{% url 'learning_logs:edit_entry' entry.id %}"  class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
      <button name="submit" class="btn btn-primary" >Save changes</button>
    {% endbuttons %}
  </form>
{% endblock content %}

<!--the edit entry page is the same with the entry pages as we are editing the old one-->

learning_logs/templates/learning_logs/entries.html
{% extends 'learning_logs\base.html' %}

{% block page_header %}
 <h3>{{ topic }}</h3>
{% endblock page_header %}

{% block content %}
<p>
  <a href="{% url 'learning_logs:new_entry' topic.id %}">Add new entry</a>
</p>
<ul>
    {% for entry in entries %}
      <div class="card mb-3">
        <h4 class="card-header">
          {{ entry.date_added|date:'M d, Y H:i' }}
          <small><a href="{% url 'learning_logs:edit_entry' entry.id %}">
          edit entry</a></small>
        </h4>
        <div class="card-body">
          {{ entry.text|linebreaks }}
        </div>
      </div>
    {%empty%}
      <p>There are no entries for this topic yet.</p>
    {%endfor%}
</ul>
{%endblock content%}

learning_logs/templates/learning_logs/index.html
{% extends "learning_logs/base.html" %}<!--this template tag tell django which template 
    to inherit from.Here it inherits from base.html -->
{% block page_header %}
    <div class="jumbotron">
        <h1 class="display-3">Track your learning.</h1>
        <p class="lead">Make your own Learning Log, and keep a list of the
            topics you're learning about. Whenever you learn something new
            about a topic, make an entry summarizing what you've learned.</p>
        <a class="btn btn-lg btn-primary" href="{% url 'users:register' %}"
            role="button">Register &raquo;</a>
     </div>
{% endblock page_header %}

learning_logs/templates/learning_logs/new_entry.html
{% extends 'learning_logs/base.html' %}
{% load bootstrap4 %}

{% block page_header %}
 <h2>Log in to your account.</h2>
{% endblock page_header %}

{% block content %}

<h3> <a href="{% url 'learning_logs:topic' topic.id %}">{{topic}}</a> </h3>

<p>Add a new entry :  </p>
<form action= "{% url 'learning_logs:new_entry' topic.id %}" method="post" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
      <button name='submit' class="btn btn-primary" >Add</button>
    {% endbuttons %}
</form>

{% endblock content%}

learning_logs/templates/learning_logs/new_topic.html
{% extends 'learning_logs/base.html' %}

{% load bootstrap4 %}

{% block page_header %}
 <h2>Log in to your account.</h2>
{% endblock page_header %}

{% block content %}
<p>Add new topic</p>
<form action= "{% url 'learning_logs:new_topic' %}" method="post" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
      <button name="submit" class="btn btn-primary" >Add topic</button>
    {% endbuttons %}

</form>

{% endblock content %}

learning_logs/templates/learning_logs/topics.html
{% extends "learning_logs/base.html" %}

{% block page_header %}
  <h1>Topics</h1>
{% endblock page_header %}
{% block content %}
<p>Topics</p>
<ul>
    {% for topic in topics %}<!--this is a template loop. we loop through the topics in the context dictionary-->
      <li><h3><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></h3></li><!--the double brace allow to print a template variable. here we print the topic variable of the loop-->
    {% empty %}<!--in case the topics is empty we print this-->
      <li><h3> no topic added yet.</h3></li>
    {% endfor %}
</ul>
<h3><a href="{% url 'learning_logs:new_topic' %}">Add a new topic</a></h3>
{% endblock content %}